# Generated by Django 3.1.4 on 2021-01-31 08:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField(max_length=500)),
                ('posted_date_project', models.DateTimeField(auto_now_add=True)),
                ('postedBy_project', models.CharField(max_length=20)),
                ('projectImage', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='aboutAuthor',
            field=models.CharField(default='', max_length=250),
        ),
    ]
