# Generated by Django 3.2.16 on 2022-12-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0003_auto_20210131_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('contact', models.IntegerField(max_length=10)),
                ('dob', models.DateField(max_length=50)),
                ('When_contacted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
