# Generated by Django 3.2.16 on 2022-12-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0004_new_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_student',
            name='When_contacted',
        ),
        migrations.AlterField(
            model_name='new_student',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
