# Generated by Django 3.2.16 on 2022-12-19 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0005_auto_20221219_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_student',
            name='When_contacted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new_student',
            name='sub',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
