# Generated by Django 3.2.16 on 2022-12-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0006_auto_20221219_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_student',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='new_student',
            name='dob',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='new_student',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='new_student',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='new_student',
            name='sub',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
