# Generated by Django 3.2.16 on 2022-12-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0007_auto_20221219_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_student',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='new_student',
            name='dob',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='new_student',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='new_student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='new_student',
            name='sub',
            field=models.CharField(max_length=50),
        ),
    ]
