# Generated by Django 3.2.16 on 2022-12-20 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0010_alter_extendeduser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='user',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
