# Generated by Django 3.2.16 on 2022-12-20 07:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0011_auto_20221220_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_teacher', models.CharField(max_length=100)),
                ('Features_of_courses', ckeditor.fields.RichTextField(default='')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('fees', models.CharField(max_length=50)),
                ('course_image', models.ImageField(default='', upload_to='course/images')),
                ('aboutTeacher', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
