# Generated by Django 3.2.16 on 2022-12-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0012_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_teacher_image',
            field=models.ImageField(default='', upload_to='courseTeacher/images'),
        ),
    ]
