# Generated by Django 3.2.16 on 2022-12-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0013_course_course_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=150)),
                ('amount', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
