# Generated by Django 3.2.16 on 2022-12-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0014_paid_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paid_Students',
            new_name='Paid_Student',
        ),
    ]
