# Generated by Django 3.2.16 on 2022-12-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp', '0017_paid_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_image', models.ImageField(default='', upload_to='story/images')),
                ('brief_content', models.CharField(max_length=300)),
            ],
        ),
    ]
